development:
  omniauth_provider_key: "843160599040453"
  omniauth_provider_secret: "81d90d729e78cb4843c4f29323c9fe69"
  domain_name: locahost
  secret_key_base: d3fa0ac307e494311c946976a9ba4d8653d90f0665a07086dc47409330e67332

test:
  secret_key_base: 4140c25db69afa137430de89e3635507c2b62d64c8202009472111383b5ab954

production:
  omniauth_provider_key: <%= ENV["OMNIAUTH_PROVIDER_KEY"] %>
  omniauth_provider_secret: <%= ENV["OMNIAUTH_PROVIDER_SECRET"] %> 
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
